#!/bin/sh

PREVIEW_WIDTH=$(($2 * 10))
PREVIEW_HEIGHT=$(($3 * 22))

case "$(file -Lb --mime-type -- "$1")" in
	video/* | image/gif)
		ffmpeg -i "$1" -frames:v 1 -vcodec png -f image2pipe - | img2sixel -w $PREVIEW_WIDTH -c "${PREVIEW_WIDTH}x${PREVIEW_HEIGHT}+0+0"
		;;
	image/*)
		img2sixel -w $PREVIEW_WIDTH -c "${PREVIEW_WIDTH}x${PREVIEW_HEIGHT}+0+0" "$1"
		;;
	application/pdf)
		pdftoppm -singlefile "$1" | img2sixel -w $PREVIEW_WIDTH -c "${PREVIEW_WIDTH}x${PREVIEW_HEIGHT}+0+0"
		;;
	application/zip)
		case "$1" in
			*.kra)
				unzip -p "$1" mergedimage.png | png2pnm | img2sixel -w $PREVIEW_WIDTH -c "${PREVIEW_WIDTH}x${PREVIEW_HEIGHT}+0+0"
				;;
			*)
				unzip -Z -2 "$1" | sort
				;;
		esac
		;;
	text/markdown)
		mdcat "$1"
		;;
	text/* | application/json)
		cat "$1"
		;;
	*)
		echo "$(file -Lb --mime-type -- "$1")"
		;;
esac
