#! /bin/sh

if test "$1" != '_CALLED_INTERNALLY'; then
	exec cmd-polkit-agent -s -c "$0 _CALLED_INTERNALLY"
else
	# Remove $1 (_CALLED_INTERNALLY) from parameter array
	shift 1

	# Read incoming messages one by one (line by line)
	while read -r msg; do
		if echo "$msg" | jq -e '.action == "request password"' 1>/dev/null 2>/dev/null; then
			# Parse msg fields
			message="$(printf '%s' "$msg" | jq -rc '.message // "No message given!"')"

			# Request a password prompt from fuzzel
			response=$(echo -e "Authentication is $(echo $message | cut -d ' ' -f 3) to \n$(echo $message | cut -d ' ' -f 5-)." | fuzzel -I -l 2 -s 2A2E32FF -S 706F6EFF -t 706F6EFF -m 706F6EFF -M 706F6EFF --no-fuzzy --password -p "Password: " -d )

			# Cancel authentication if no password was given, otherwise respond with given password
			if test -z "$response"; then
				echo '{"action":"cancel"}'
			else
				echo "{\"action\":\"authenticate\",\"password\": \"$response\"}"
			fi
		fi
	done
fi
