#!/bin/bash

function powermenu {
	options="Cancel\nSleep\nReboot\nShut down"
	selected=$(echo -e $options | dmenu)
	if [[ $selected = "Shut down" ]]; then
		systemctl poweroff
	elif [[ $selected = "Reboot" ]]; then
		systemctl reboot
	elif [[ $selected = "Sleep" ]]; then
		systemctl suspend
	elif [[ $selected = "Cancel" ]]; then
		return
	fi
}

powermenu
