#!/bin/sh

cd ~

# Log WLR errors and logs to the hyprland log. Recommended
export HYPRLAND_LOG_WLR=1

# Graphics stuff
export MOZ_ENABLE_WAYLAND=1
export SDL_VIDEODRIVER="wayland,x11"

# Tell XWayland to use a cursor theme
export XCURSOR_THEME=Breeze_Snow
export XCURSOR_SIZE=32

export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_CURRENT_DESKTOP=hyprland

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=qt5ct

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx

export GDK_DEBUG=portals
export GTK_USE_PORTAL=1
export BROWSER="firefox-developer-edition"

export LC_ALL="en_AU.UTF-8"

exec Hyprland

