#!/bin/bash

check_ac_adapter() {
	case $(cat /sys/class/power_supply/ACAD/online) in
		0)
			hyprctl keyword monitor eDP-1,1920x1080@60,0x0,1
		;;
		1)
			hyprctl keyword monitor eDP-1,1920x1080@120,0x0,1
		;;
	esac
}

while true; do check_ac_adapter; sleep 30; done
